language: go
go:
 - 1.x
 - tip

go_import_path: github.com/appscode/searchlight

install: true

script:
  - go build ./...
  - ./hack/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
